# Generated by Django 4.0.2 on 2022-02-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('picture_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_procedures',
                'managed': False,
            },
        ),
    ]
