# Generated by Django 4.0.2 on 2022-02-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosmetik', '0002_alter_procedure_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_title', models.CharField(max_length=255, verbose_name='Titel (DEU)')),
                ('de_title', models.CharField(max_length=255, verbose_name='Title (ENG)')),
                ('ru_title', models.CharField(max_length=255, verbose_name='Название (RUS)')),
            ],
            options={
                'verbose_name': 'Категория процедуры',
                'verbose_name_plural': 'Категории процедур',
                'db_table': 'tbl_category_procedures',
                'managed': False,
            },
        ),
    ]
